// Centralised mock data for all features.
// In production these would be replaced with API calls / server components.

import {
  Package,
  CheckCircle,
  XCircle,
  Users,
  ShieldCheck,
  AlertCircle,
} from "lucide-react";
import type {
  AdminItem,
  AdminClaim,
  AdminUser,
  Item,
  Notification,
} from "./types";

// ─── Admin ────────────────────────────────────────────────────────────────────

export const ADMIN_ITEMS: AdminItem[] = [
  {
    id: "i1",
    name: 'MacBook Pro 14"',
    category: "Electronics",
    location: "Library, 3F",
    status: "found",
    reportedBy: "Alex R.",
    date: "Feb 22",
    claims: 2,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
  {
    id: "i2",
    name: "Sony XM4 Headphones",
    category: "Electronics",
    location: "Cafeteria B",
    status: "lost",
    reportedBy: "Maya P.",
    date: "Feb 23",
    claims: 0,
    color: "#FDE8D8",
    text: "#C2622A",
  },
  {
    id: "i3",
    name: "House Keys (Blue Lanyard)",
    category: "Keys",
    location: "Engineering Blk",
    status: "resolved",
    reportedBy: "Rohan K.",
    date: "Feb 10",
    claims: 1,
    color: "#D4F4DC",
    text: "#2E7D45",
  },
  {
    id: "i4",
    name: "Campus ID STU-7821",
    category: "Documents",
    location: "Admin Block",
    status: "found",
    reportedBy: "Sam T.",
    date: "Feb 21",
    claims: 1,
    color: "#EDE8FD",
    text: "#6B3EDE",
  },
  {
    id: "i5",
    name: "HP Pavilion Charger",
    category: "Electronics",
    location: "Library, 2F",
    status: "claimed",
    reportedBy: "Divya S.",
    date: "Feb 19",
    claims: 1,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
  {
    id: "i6",
    name: "Blue Hydroflask 32oz",
    category: "Accessories",
    location: "Library, 3F",
    status: "resolved",
    reportedBy: "Priya M.",
    date: "Feb 10",
    claims: 1,
    color: "#FDE8D8",
    text: "#C2622A",
  },
  {
    id: "i7",
    name: "TI-84 Calculator",
    category: "Electronics",
    location: "Maths Block R303",
    status: "lost",
    reportedBy: "Jay B.",
    date: "Feb 23",
    claims: 0,
    color: "#EDE8FD",
    text: "#6B3EDE",
  },
  {
    id: "i8",
    name: "Red Umbrella",
    category: "Accessories",
    location: "Main Gate",
    status: "found",
    reportedBy: "Nisha K.",
    date: "Feb 22",
    claims: 0,
    color: "#FDE8D8",
    text: "#C2622A",
  },
];

export const ADMIN_CLAIMS: AdminClaim[] = [
  {
    id: "c1",
    item: 'MacBook Pro 14"',
    claimer: "Maya P.",
    finder: "Alex R.",
    status: "pending",
    submitted: "Feb 23",
    message: "My laptop, scratch on lid, serial starts C02ZK.",
  },
  {
    id: "c2",
    item: "Campus ID STU-7821",
    claimer: "Raj S.",
    finder: "Sam T.",
    status: "approved",
    submitted: "Feb 21",
    message: "My student ID, I can show verification on my phone.",
  },
  {
    id: "c3",
    item: "HP Pavilion Charger",
    claimer: "Anika V.",
    finder: "Divya S.",
    status: "pending",
    submitted: "Feb 20",
    message: "Blue HP charger with a tape label 'A.V.' near the plug.",
  },
  {
    id: "c4",
    item: "House Keys",
    claimer: "Karan M.",
    finder: "Rohan K.",
    status: "rejected",
    submitted: "Feb 11",
    message: "Had Stanford 2025 lanyard.",
  },
  {
    id: "c5",
    item: "Sony XM4 Headphones",
    claimer: "Leena T.",
    finder: "Maya P.",
    status: "pending",
    submitted: "Feb 23",
    message: "Midnight black, guitar-pick keychain on case.",
  },
];

export const ADMIN_USERS: AdminUser[] = [
  {
    id: "u1",
    name: "Maya Patel",
    email: "maya@stanford.edu",
    role: "student",
    joined: "Sep 2024",
    reports: 3,
    claims: 5,
    active: true,
  },
  {
    id: "u2",
    name: "Alex Ramirez",
    email: "alex@stanford.edu",
    role: "student",
    joined: "Aug 2023",
    reports: 7,
    claims: 2,
    active: true,
  },
  {
    id: "u3",
    name: "Priya Mehta",
    email: "priya@stanford.edu",
    role: "student",
    joined: "Jan 2025",
    reports: 1,
    claims: 3,
    active: true,
  },
  {
    id: "u4",
    name: "Rohan Kumar",
    email: "rohan@stanford.edu",
    role: "staff",
    joined: "Mar 2022",
    reports: 12,
    claims: 0,
    active: true,
  },
  {
    id: "u5",
    name: "Divya Sharma",
    email: "divya@stanford.edu",
    role: "student",
    joined: "Sep 2024",
    reports: 2,
    claims: 1,
    active: false,
  },
  {
    id: "u6",
    name: "Sam Thompson",
    email: "sam@stanford.edu",
    role: "admin",
    joined: "Jan 2022",
    reports: 0,
    claims: 0,
    active: true,
  },
  {
    id: "u7",
    name: "Karan Mehta",
    email: "karan@stanford.edu",
    role: "student",
    joined: "Aug 2024",
    reports: 1,
    claims: 4,
    active: true,
  },
  {
    id: "u8",
    name: "Leena Thomas",
    email: "leena@stanford.edu",
    role: "student",
    joined: "Sep 2023",
    reports: 2,
    claims: 2,
    active: true,
  },
];

export const ADMIN_ACTIVITY = [
  {
    title: 'New found report: MacBook Pro 14"',
    description: "Reported by Alex R. at Library, 3F.",
    timestamp: "2 min ago",
    color: "blue" as const,
    icon: <Package className="w-4 h-4" />,
  },
  {
    title: "Claim approved: Campus ID",
    description: "Raj S.'s claim verified by Sam T.",
    timestamp: "18 min ago",
    color: "green" as const,
    icon: <CheckCircle className="w-4 h-4" />,
  },
  {
    title: "New user registered",
    description: "Leena Thomas joined from stanford.edu.",
    timestamp: "1 hr ago",
    color: "default" as const,
    icon: <Users className="w-4 h-4" />,
  },
  {
    title: "Claim rejected: House Keys",
    description: "Karan M.'s claim could not be verified.",
    timestamp: "3 hr ago",
    color: "red" as const,
    icon: <XCircle className="w-4 h-4" />,
  },
  {
    title: "Item resolved: Hydroflask",
    description: "Successfully returned to Priya M.",
    timestamp: "5 hr ago",
    color: "green" as const,
    icon: <ShieldCheck className="w-4 h-4" />,
  },
  {
    title: "Flag raised: suspicious claim",
    description: "Auto-flagged for admin review on item i7.",
    timestamp: "8 hr ago",
    color: "amber" as const,
    icon: <AlertCircle className="w-4 h-4" />,
  },
];

// ─── Items directory ──────────────────────────────────────────────────────────

export const DIRECTORY_ITEMS: Item[] = [
  {
    id: "1",
    name: 'Space Gray MacBook Pro 14"',
    category: "Electronics",
    location: "Library, 3F",
    status: "found",
    daysAgo: 1,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
  {
    id: "2",
    name: "Sony WH-1000XM4 Headphones",
    category: "Electronics",
    location: "Cafeteria, Block B",
    status: "found",
    daysAgo: 2,
    color: "#FDE8D8",
    text: "#C2622A",
  },
  {
    id: "3",
    name: "Blue Hydroflask 32oz",
    category: "Accessories",
    location: "Library, 3F",
    status: "lost",
    daysAgo: 3,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
  {
    id: "4",
    name: "House Keys (Blue Lanyard)",
    category: "Keys",
    location: "Engineering Block, 2F",
    status: "found",
    daysAgo: 1,
    color: "#D4F4DC",
    text: "#2E7D45",
  },
  {
    id: "5",
    name: "Campus ID — STU-7821",
    category: "Documents",
    location: "Admin Block",
    status: "found",
    daysAgo: 4,
    color: "#EDE8FD",
    text: "#6B3EDE",
  },
  {
    id: "6",
    name: "TI-84 Calculator",
    category: "Electronics",
    location: "Maths Block, R303",
    status: "lost",
    daysAgo: 2,
    color: "#EDE8FD",
    text: "#6B3EDE",
  },
  {
    id: "7",
    name: "HP Pavilion 15 Charger",
    category: "Electronics",
    location: "Library, 2F",
    status: "found",
    daysAgo: 2,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
  {
    id: "8",
    name: "Stethoscope (Medical Dept.)",
    category: "Medical",
    location: "Medical Sciences, B1",
    status: "found",
    daysAgo: 6,
    color: "#D4F4DC",
    text: "#2E7D45",
  },
  {
    id: "9",
    name: "Red Umbrella",
    category: "Accessories",
    location: "Main Gate",
    status: "found",
    daysAgo: 3,
    color: "#FDE8D8",
    text: "#C2622A",
  },
  {
    id: "10",
    name: "Black North Face Backpack",
    category: "Bags",
    location: "Sports Complex",
    status: "lost",
    daysAgo: 5,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
  {
    id: "11",
    name: "Lab Notebook (BIO-301)",
    category: "Documents",
    location: "Medical Sciences, 2F",
    status: "found",
    daysAgo: 1,
    color: "#D4F4DC",
    text: "#2E7D45",
  },
  {
    id: "12",
    name: "Reading Glasses (Black Frame)",
    category: "Accessories",
    location: "Library, 1F",
    status: "found",
    daysAgo: 2,
    color: "#C8DFFE",
    text: "#3B7FD4",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    kind: "claim",
    title: "New claim on your item",
    body: 'Maya Patel submitted a claim on "MacBook Pro 14″" you found at the library.',
    time: "2 min ago",
    read: false,
    actor: "Maya Patel",
    actionLabel: "Review claim",
    actionHref: "/claims",
  },
  {
    id: "n2",
    kind: "approved",
    title: "Your claim was approved!",
    body: 'Alex R. approved your claim on "Sony WH-1000XM4 Headphones". Coordinate a handoff.',
    time: "18 min ago",
    read: false,
    actor: "Alex R.",
    actionLabel: "Arrange handoff",
    actionHref: "/claims",
  },
  {
    id: "n3",
    kind: "match",
    title: "Possible match found",
    body: 'A newly reported found item resembles "Blue Hydroflask 32oz" you reported lost. Check it out.',
    time: "1 hr ago",
    read: false,
    actionLabel: "View item",
    actionHref: "/items",
  },
  {
    id: "n4",
    kind: "handoff",
    title: "Handoff reminder",
    body: 'You have a pending handoff for "TI-84 Calculator" with Sam T. — arrange pickup today.',
    time: "3 hr ago",
    read: true,
    actor: "Sam T.",
    actionLabel: "Message finder",
    actionHref: "/claims",
  },
  {
    id: "n5",
    kind: "resolved",
    title: "Item marked as resolved",
    body: '"House Keys (Blue Lanyard)" was successfully returned. Thanks for using CampusClaim!',
    time: "Yesterday",
    read: true,
  },
  {
    id: "n6",
    kind: "claim",
    title: "Claim rejected on your report",
    body: 'A claim on your found item "Red Umbrella" was rejected after verification.',
    time: "Yesterday",
    read: true,
    actionLabel: "View report",
    actionHref: "/items",
  },
  {
    id: "n7",
    kind: "system",
    title: "Welcome to CampusClaim!",
    body: "Your account is verified and ready. Start by browsing found items or reporting something lost.",
    time: "Feb 10",
    read: true,
    actionLabel: "Browse items",
    actionHref: "/items",
  },
];
